### ISSUE TITLE
Rename Question Was Opened to Question Round Was Started

### ISSUE THREAD

**Issue by michelgrootjans** [tcoopman/playing_with_projections_server#1]

**Comment by tcoopman** [comment]
Hmm. Not sure yet. Can we find other names too? Don't we also need to rename other events too?

**Comment by tcoopman** [comment]
Round sounds like a group of questions

**Comment by michelgrootjans** [comment]
Question Was Asked

**Comment by tcoopman** [comment]
Ok, then the 2 closing events still are:
TimerRung? BellHasRung? QuestionTimedOut? --> TimerHasExpired

QuestionWasClosed --> QuestionWasCompleted

**Comment by tcoopman** [comment]
see #2

**Comment by tcoopman** [comment]
Fixed by #2
